# Generated by Django 3.1.3 on 2020-12-20 16:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('featured', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('video_display', models.BooleanField()),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='packages', to='posts.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
