# Generated by Django 3.1.3 on 2021-01-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201228_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '5. CATÉGORIES'},
        ),
    ]
