# Generated by Django 3.1.2 on 2020-10-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_added',
            new_name='%m/%Y',
        ),
    ]
