# Generated by Django 3.1.2 on 2020-10-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201029_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='%m/%Y',
            new_name='date_added',
        ),
    ]
