# Generated by Django 3.1 on 2020-10-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
