# Generated by Django 3.1 on 2020-10-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201031_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumnail',
            field=models.FileField(upload_to=''),
        ),
    ]
