# Generated by Django 3.1 on 2020-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201031_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumnail', models.ImageField(upload_to='')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='thumnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
