# Generated by Django 3.1 on 2020-11-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201101_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
    ]
