# Generated by Django 3.1 on 2020-11-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
