# Generated by Django 3.1 on 2020-11-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201104_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='post',
            new_name='Event',
        ),
    ]
