# Generated by Django 3.1 on 2020-11-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20201104_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='Event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.DeleteModel(
            name='event',
        ),
    ]
