# Generated by Django 3.1 on 2020-11-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201106_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='Event',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='posts/'),
        ),
    ]
