# Generated by Django 3.1.3 on 2020-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20201216_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_display',
            field=models.BooleanField(default=False),
        ),
    ]
