# Generated by Django 3.1.3 on 2020-12-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_video_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_display',
            field=models.BooleanField(),
        ),
    ]
