# Generated by Django 3.1.3 on 2020-12-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20201217_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentcount',
        ),
    ]
