# Generated by Django 3.1.3 on 2020-12-29 10:50

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('overview', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('video_display', models.BooleanField()),
                ('image_display', models.BooleanField(default=False)),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
            ],
        ),
    ]
