# Generated by Django 3.1.3 on 2020-12-16 22:05

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20201115_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
