# Generated by Django 3.1.3 on 2020-12-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_display',
            field=models.BooleanField(default=0, verbose_name=False),
            preserve_default=False,
        ),
    ]
