# Generated by Django 3.1.3 on 2020-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20201115_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
