# Generated by Django 3.1.3 on 2020-11-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_member_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
    ]
