# Generated by Django 3.1.3 on 2020-11-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_remove_member_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
