# Generated by Django 3.1.3 on 2020-11-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20201115_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
    ]
