# Generated by Django 3.1.3 on 2020-12-14 18:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nextevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=150)),
                ('eventdate', models.CharField(max_length=150)),
                ('eventtime', models.CharField(max_length=150)),
                ('eventloction1', models.CharField(max_length=150)),
                ('thumnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
