# Generated by Django 3.1.3 on 2020-12-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextevent', '0002_auto_20201214_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextevent',
            old_name='eventdate1',
            new_name='eventdate',
        ),
        migrations.RenameField(
            model_name='nextevent',
            old_name='eventloction1',
            new_name='eventloction',
        ),
        migrations.RenameField(
            model_name='nextevent',
            old_name='eventname1',
            new_name='eventname',
        ),
        migrations.RenameField(
            model_name='nextevent',
            old_name='eventtime1',
            new_name='eventtime',
        ),
        migrations.RenameField(
            model_name='nextevent',
            old_name='thumnail1',
            new_name='thumnail',
        ),
    ]
