# Generated by Django 3.1.3 on 2021-01-17 20:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0018_theme_list_filter_sticky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='(.ico|.png|.gif - 16x16|32x32 px)', max_length=255, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Leave blank to use the default Django logo', max_length=255, verbose_name='logo'),
        ),
    ]
